# Generated by Django 5.0a1 on 2023-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('read', models.BooleanField()),
                ('date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
