# Generated by Django 5.0a1 on 2023-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
