# Generated by Django 5.0a1 on 2023-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_upload_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('RESTAURANT', 'Restaurant'), ('CLIENT', 'Client')], default='ADMIN', max_length=10),
        ),
    ]
