# Generated by Django 5.0a1 on 2023-11-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('vegetarian', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('celiac', models.BooleanField()),
                ('dish_image', models.ImageField(blank=True, upload_to='')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_dishes', to='login.restaurant')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='dishes_with', to='main.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='login.client')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ratings', to='main.dish')),
            ],
            options={
                'unique_together': {('client', 'dish')},
            },
        ),
    ]
