# Generated by Django 5.0a1 on 2023-11-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_latose_free_dish_nuts_free_rating_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='latose_free',
            new_name='lactose_free',
        ),
    ]
